# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "hello, world from " $FIRST_ENV_VAR > output.txt 
              
      - persist_to_workspace:
          root: /~
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: /~
      - run: cat output.txt  

workflows:
  default:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
     