version: 2.1

commands: 
  print_pipeline_id:
    description: "use reusable code to print an env var"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "hello, world from " $FIRST_ENV_VAR > ./output.txt 
      - persist_to_workspace:
          root: home/circleci
          paths:
            - ./
      
      - run: 
            command: echo "Build failed"
            when: on_fail

  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: ./output.txt
      - run: cat ./output.txt 

  new_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id

workflows:
  default:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - new_job
     